### PR TITLE
Dockerfile working dir fix

### LINKED ISSUE #75: Dockerfile can't initialise container
running docker build . -t covid on a fresh checkout fails. I think it is because "devtools::install_dev_deps()" is unable to find the DESCRIPTION file - it complains about being unable to find "" (helpfully). Setting WORKDIR in the dockerfile seems to resolve this.

I will open a PR with a fix shortly.

### PR DESCRIPTION
**Pull request by joeHickson**
fixes #75 
includes documentation update

### CODE REVIEW

**Comment by joeHickson** [comment]
@seabbs I could see in the history. Don't worry, it's still not copying the code in, just specifying where RUN Rscript -e "devtools::install_dev_deps()" is executed so that it can find the DESCRIPTION file to know what the required modules are to install. I then mount the code when I launch the docker image (as per the readme).
I'm working towards being able to check out a completely fresh copy of the code, build the docker as per the dockerfile / description file and then mount and run the code within it. 
The CI tools may also benefit from something I changed when locally building it - shifting the two files (dockerfile and DESCRIPTION) into a separate folder stopped docker build publishing the whole of the checked out git repo structure as the context (28gb or so) and instead just publishes the two files as the context (just a few kb).

**Comment by seabbs** [comment]
Ah sounds great! The folder shift sounds like a good idea though does make it a bit nonstandard as an R code repo so would need a pointer for the DESCRIPTION.

**Comment by joeHickson** [comment]
oh yes, leaving DESCRIPTION in the root of the project really! I am doing the shuffling locally - I'll have a look into how we can do it on pipelines (this can't be the first project to not want all the code as docker context)

**Comment by joeHickson** [comment]
I have a solution - ticket, branch and fix to follow.

**Pull request merged**
